name: Build & Publish

on:
  release:
    types:
      - released

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --no-dev

      - name: Run linters
        run: uvx ruff format --check && uvx ruff check

      - name: Build wheel
        run: uv build

      - name: Save wheel
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/*.whl

  release:
    name: Release package to PyPI
    runs-on: ubuntu-latest
    environment: release
    steps:
       - name: Publish package
         run: uv publish

